name: Go Matrix
on: [push, pull_request]

jobs:

  cross:
    name: Go
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0

    strategy:
      matrix:
        go-version: [ oldstable, stable ]
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: ['x32', 'x64']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          architecture: ${{ matrix.arch }}

      - name: Test
        run: go test -v -cover ./...
